version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: postgres_java_container
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234567890"
      POSTGRES_DB: "shopdevjavav1"
    ports:
      - "55432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork
volumes:
  postgres_data:
networks:
  mynetwork:
    driver: bridge